[tox]
env_list = lint, main

[vars]
src_path = {tox_root}/src {tox_root}/rest
all_path = main.py {[vars]src_path} {tox_root}/tests

[testenv]
set_env =
    PY_COLORS = 1
    PYTHONPATH = {tox_root}/src
    file|.env
allowlist_externals =
    uv
    uvx

[testenv:format]
description = Apply coding style standards to code
commands =
    uvx ruff check  --config pyproject.toml --fix {[vars]all_path}
    uvx ruff format --config pyproject.toml {[vars]all_path}


[testenv:lint]
description = Check code against coding style standards
commands =
    uvx codespell --skip="*.json" --toml {tox_root}/pyproject.toml {[vars]all_path}
    uvx ruff check --config {tox_root}/pyproject.toml {[vars]all_path}
    uvx ruff format --check --config {tox_root}/pyproject.toml --diff {[vars]all_path}
    uv run pyright {[vars]src_path}


[testenv:repl]
commands =
    uv run python3 -i {posargs}


[testenv:workflow]
commands =
    uv run python3 main.py {posargs}


[testenv:rest]
passenv = PORT
commands =
    uv run python3 run.py {posargs}


[testenv:unit-tests]
description = Run unit tests
commands_pre =
    uv sync --frozen
commands =
    uv run coverage run \
        --source={tox_root}/src \
        -m pytest \
        -s \
        -m "not integration" \
        -vv \
        {tox_root}/tests \
        {posargs}
    uv run coverage report


[testenv:integration-tests]
description = Run integration tests
commands_pre =
    uv sync --frozen
commands =
    uv run coverage run \
        --source={tox_root}/src \
        -m pytest \
        -s \
        -m integration \
        -vv \
        {tox_root}/tests \
        {posargs}
    uv run coverage report


[testenv:tests]
description = Run all tests
commands_pre =
    uv sync --frozen
commands =
    uv run coverage run \
        --source={tox_root}/src \
        -m pytest \
        -s \
        -vv \
        {tox_root}/tests \
        {posargs}
    uv run coverage report
